#!/bin/sh

echo "Axway API-Manager Report tool"
echo ""  
echo "It allows you to create different reports based on your API-Manager registry." 
echo ""
echo "Available reports today (may has been extended already):" 
echo "  CSVEmbeddedAnalyticsReport:"
echo "  Generates a report with APIs, Applications, Orgs and their relation to each other. (CSV-Format)"
echo ""
echo "  CSVCustomPolicyDependencyReport:"
echo "  Tells you which APIs are using which Custom-Policies (CSV-Format)"
echo ""
echo "  ExcelCustomPolicyDependencyReport:"
echo "  Tells you which APIs are using which Custom-Policies (Excel-Format)"
echo ""
echo ""
echo "The Report tool is now separated from Swagger-Promote. You can download it from here:" 
echo "https://github.com/Axway-API-Management-Plus/apimanager-report-tool"
echo ""
echo "More documentation is here:" 
echo "https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/8.-API-Manager-Report-tool"