name: Bug report
description: Create a report to help us to improve the API-Manager CLI
labels: [bug]
assignees:
  - cwiechmann
body:
  - type: markdown
    attributes:
      value: |
        :raised_hand: The handling procedure for issues has changed. If you need immediate support, please open an Axway support case instead.
        ---
        
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: input
    id: apimcliVersion
    attributes:
      label: APIM-CLI version
      description: "The APIM-CLI version you are using"
      placeholder: "1.10.1"
    validations:
      required: true
  - type: input
    id: apimanagementVersion
    attributes:
      label: API-Management version
      description: "The API-Management version you are using"
      placeholder: "7.7.0.20220228"
    validations:
      required: true  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Which steps do we need to take to reproduce this error?
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell