name: Feature request
description: Tell us what you need and why in the API-Mgr. CLI
labels: [enhancement]
assignees:
  - cwiechmann
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: false
  - type: textarea
    id: feature-request
    attributes:
      label: Feature request
      description: Describe the solution you'd like
    validations:
      required: true