package com.axway.apim.test.apimethods;

import com.axway.apim.EndpointConfig;
import com.axway.apim.export.test.ExportTestAction;
import com.axway.apim.test.ImportTestAction;
import com.jayway.jsonpath.DocumentContext;
import com.jayway.jsonpath.JsonPath;
import org.citrusframework.annotations.CitrusResource;
import org.citrusframework.annotations.CitrusTest;
import org.citrusframework.context.TestContext;
import org.citrusframework.functions.core.RandomNumberFunction;
import org.citrusframework.http.client.HttpClient;
import org.citrusframework.testng.spring.TestNGCitrusSpringSupport;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import static org.citrusframework.DefaultTestActionBuilder.action;
import static org.citrusframework.actions.EchoAction.Builder.echo;
import static org.testng.Assert.assertEquals;


@ContextConfiguration(classes = {EndpointConfig.class})
public class ExportApiMethodsIT  extends TestNGCitrusSpringSupport {

    @Autowired
    HttpClient apiManager;

    @CitrusTest
    @Test
    @Parameters("context")
    public void run(@Optional @CitrusResource TestContext context) throws IOException {
        ImportTestAction importTestAction = new ImportTestAction();
        ExportTestAction exportTestAction = new ExportTestAction();
        variable("apiNumber", RandomNumberFunction.getRandomNumber(4, true));
        variable("apiPath", "/basic-api-method-level-api-${apiNumber}");
        variable("apiName", "API Method-Export-${apiNumber}");
        variable("exportLocation", "citrus:systemProperty('java.io.tmpdir')");
        variable(ExportTestAction.EXPORT_API, "${apiPath}");

        // These are the folder and filenames generated by the export tool
        variable("exportFolder", "api-test-${apiName}");
        variable("exportAPIName", "${apiName}.json");

        $(echo("####### Try to replicate an API having Method-Level settings declared #######"));
        variable(ImportTestAction.API_DEFINITION, "/com/axway/apim/test/files/basic/petstore.json");
        variable(ImportTestAction.API_CONFIG, "/com/axway/apim/test/files/apimethods/api_methods_export.json");
        variable("state", "published");
        variable("expectedReturnCode", "0");
        variable("securityProfileName", "APIKeyBased${apiNumber}");
        $(action(importTestAction));

        $(echo("####### Export the API including applications from the API-Manager #######"));
        variable("expectedReturnCode", "0");
        variable("exportMethods", "true");
        $(action(exportTestAction));

        String exportedAPIConfigFile = context.getVariable("exportLocation") + "/" + context.getVariable("apiPath") + "/api-config.json";
        $(echo("Exported config file location " + exportedAPIConfigFile));
        $(echo("####### Reading exported API-Config file: '" + exportedAPIConfigFile + "' #######"));
        DocumentContext documentContext = JsonPath.parse(new File(exportedAPIConfigFile));
        assertEquals(documentContext.read("$.version", String.class), "1.0.7");
        assertEquals(documentContext.read("organization", String.class), "API Development " + context.getVariable("orgNumber"));
        assertEquals(documentContext.read("state", String.class), "published");
        assertEquals(documentContext.read("path", String.class), context.getVariable("apiPath"));
        assertEquals(documentContext.read("name", String.class), context.getVariable("apiName"));
        assertEquals(documentContext.read("apiMethods", ArrayList.class).size(), 20);
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='createUser')].name", ArrayList.class).get(0), "createUser");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='logoutUser')].name", ArrayList.class).get(0), "logoutUser");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='deleteOrder')].name", ArrayList.class).get(0), "deleteOrder");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='updateUser')].name", ArrayList.class).get(0), "updateUser");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='getOrderById')].name", ArrayList.class).get(0), "getOrderById");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='updatePetWithForm')].name", ArrayList.class).get(0), "updatePetWithForm");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='getPetById')].name", ArrayList.class).get(0), "getPetById");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='loginUser')].name", ArrayList.class).get(0), "loginUser");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='getUserByName')].name", ArrayList.class).get(0), "getUserByName");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='getInventory')].name", ArrayList.class).get(0), "getInventory");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='createUsersWithArrayInput')].name", ArrayList.class).get(0), "createUsersWithArrayInput");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='deleteUser')].name", ArrayList.class).get(0), "deleteUser");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='findPetsByStatus')].name", ArrayList.class).get(0), "findPetsByStatus");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='deletePet')].name", ArrayList.class).get(0), "deletePet");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='placeOrder')].name", ArrayList.class).get(0), "placeOrder");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='updatePet')].name", ArrayList.class).get(0), "updatePet");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='addPet')].name", ArrayList.class).get(0), "addPet");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='createUsersWithListInput')].name", ArrayList.class).get(0), "createUsersWithListInput");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='uploadFile')].name", ArrayList.class).get(0), "uploadFile");
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='findPetsByTags')].name", ArrayList.class).get(0), "findPetsByTags");
    }
}
