package com.axway.apim.test.apimethods;

import com.axway.apim.EndpointConfig;
import com.axway.apim.export.test.ExportTestAction;
import com.axway.apim.test.ImportTestAction;
import com.jayway.jsonpath.DocumentContext;
import com.jayway.jsonpath.JsonPath;
import org.citrusframework.annotations.CitrusResource;
import org.citrusframework.annotations.CitrusTest;
import org.citrusframework.context.TestContext;
import org.citrusframework.functions.core.RandomNumberFunction;
import org.citrusframework.http.client.HttpClient;
import org.citrusframework.testng.spring.TestNGCitrusSpringSupport;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.testng.annotations.Optional;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;

import static org.citrusframework.actions.EchoAction.Builder.echo;
import static org.testng.Assert.assertEquals;


@ContextConfiguration(classes = {EndpointConfig.class})
public class ImportApiMethodsWithTagsIT extends TestNGCitrusSpringSupport {

    @Autowired
    HttpClient apiManager;

    @CitrusTest
    @Test
    @Parameters("context")
    public void run(@Optional @CitrusResource TestContext context) throws IOException {
        ImportTestAction importTestAction = new ImportTestAction();
        ExportTestAction exportTestAction = new ExportTestAction();
        variable("apiNumber", RandomNumberFunction.getRandomNumber(4, true));
        variable("apiPath", "/basic-api-method-level-api-${apiNumber}");
        variable("apiName", "API Method-Export-${apiNumber}");
        variable("exportLocation", "citrus:systemProperty('java.io.tmpdir')");
        variable(ExportTestAction.EXPORT_API, "${apiPath}");

        // These are the folder and filenames generated by the export tool
        variable("exportFolder", "api-test-${apiName}");
        variable("exportAPIName", "${apiName}.json");

        $(echo("####### Try to replicate an API having Method-Level settings declared #######"));
        variable(ImportTestAction.API_DEFINITION, "/com/axway/apim/test/files/basic/petstore.json");
        variable(ImportTestAction.API_CONFIG, "/com/axway/apim/test/files/apimethods/api_methods_with_tags.json");
        variable("state", "published");
        variable("expectedReturnCode", "0");
        variable("securityProfileName", "APIKeyBased${apiNumber}");
        importTestAction.doExecute(context);

        $(echo("####### Export the API including applications from the API-Manager #######"));
        variable("exportMethods", "true");
        variable("expectedReturnCode", "0");
        exportTestAction.doExecute(context);

        String exportedAPIConfigFile = context.getVariable("exportLocation") + "/" + context.getVariable("apiPath") + "/api-config.json";
        $(echo("Exported config file location " + exportedAPIConfigFile));
        $(echo("####### Reading exported API-Config file: '" + exportedAPIConfigFile + "' #######"));
        DocumentContext documentContext = JsonPath.parse(new File(exportedAPIConfigFile));
        assertEquals(documentContext.read("$.version", String.class), "1.0.7");
        assertEquals(documentContext.read("organization", String.class), "API Development " + context.getVariable("orgNumber"));
        assertEquals(documentContext.read("state", String.class), "published");
        assertEquals(documentContext.read("path", String.class), context.getVariable("apiPath"));
        assertEquals(documentContext.read("name", String.class), context.getVariable("apiName"));
        assertEquals(documentContext.read("apiMethods", ArrayList.class).size(), 20);
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='createUser')].tags.stage", ArrayList.class).get(0), Collections.singletonList("dev"));
        assertEquals(documentContext.read("$.apiMethods[?(@.name=='logoutUser')].tags.stage", ArrayList.class).get(0), Collections.singletonList("dev"));
    }
}
