name: API-Manager CLI tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Run Unit tests
      run: mvn clean test

  start-cassandra:
    needs: [run-unit-tests]
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Cassandra
      uses: addnab/docker-run-action@v3
      with:
        image: cassandra:2.2.12