name: API-Manager CLI tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Unit tests
      run: mvn clean test

  Run-Integration tests:
    needs: [run-unit-tests]
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start Cassandra
      uses: addnab/docker-run-action@v3
      with:
        image: cassandra:2.2.12
    - name: Start API-Management
      uses: addnab/docker-run-action@v3
      with:
        username: ${{ secrets.AXWAY_DOCKER_REG_USER }}
        password: ${{ secrets.AXWAY_DOCKER_REG_PASS }}
        registry: docker-registry.demo.axway.com
        image: swagger-promote/api-mgr-with-policies:7.6.2-SP5